### ISSUE TITLE
Remove-MSISource cannot remove a path if it does not exist

### ISSUE THREAD

**Issue by heaths** [heaths/psmsi#21]
The cmdlet fails if the path does not exist whether through the pipeline or explicit parameter values:

```
remove-msisource : Cannot find path 'C:\ProgramData\...\example\' because it does not exist.
```

**Comment by heaths** [comment]
From the stack:
```
$Error[0].Exception.StackTrace
   at System.Management.Automation.LocationGlobber.ExpandMshGlobPath(String path, Boolean allowNonexistingPaths, PSDriveInfo drive, ContainerCmdletProvider provider, CmdletProviderContext context)
   at System.Management.Automation.LocationGlobber.ResolveDriveQualifiedPath(String path, CmdletProviderContext context, Boolean allowNonexistingPaths, CmdletProvider& providerInstance)
   at System.Management.Automation.LocationGlobber.GetGlobbedMonadPathsFromMonadPath(String path, Boolean allowNonexistingPaths, CmdletProviderContext context, CmdletProvider& providerInstance)
   at System.Management.Automation.LocationGlobber.GetGlobbedProviderPathsFromMonadPath(String path, Boolean allowNonexistingPaths, CmdletProviderContext context, ProviderInfo& provider, CmdletProvider& providerInstance)
   at System.Management.Automation.SessionStateInternal.GetItem(String[] paths, CmdletProviderContext context)
   at System.Management.Automation.SessionStateInternal.GetItem(String[] paths, Boolean force, Boolean literalPath)
   at Microsoft.Tools.WindowsInstaller.PowerShell.Commands.SourcePathCommandBase.UpdateParameters(Parameters param)
   at Microsoft.Tools.WindowsInstaller.PowerShell.Commands.SourceCommandBase.ProcessRecord()
   at System.Management.Automation.Cmdlet.DoProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
```
Since this is in `SourcePathCommandBase` it affects `Add-MSISource` as well, and front-loading sources even before they exist could be useful in some cases. Need to consider not requiring the paths in either case but still need to resolve paths.
